/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiverIndexRouteImport } from './routes/receiver.index'
import { Route as DonorIndexRouteImport } from './routes/donor.index'
import { Route as ReceiverClaimedRouteImport } from './routes/receiver.claimed'
import { Route as DonorCreateRouteImport } from './routes/donor.create'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiverIndexRoute = ReceiverIndexRouteImport.update({
  id: '/receiver/',
  path: '/receiver/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorIndexRoute = DonorIndexRouteImport.update({
  id: '/donor/',
  path: '/donor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiverClaimedRoute = ReceiverClaimedRouteImport.update({
  id: '/receiver/claimed',
  path: '/receiver/claimed',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorCreateRoute = DonorCreateRouteImport.update({
  id: '/donor/create',
  path: '/donor/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/donor/create': typeof DonorCreateRoute
  '/receiver/claimed': typeof ReceiverClaimedRoute
  '/donor/': typeof DonorIndexRoute
  '/receiver/': typeof ReceiverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/donor/create': typeof DonorCreateRoute
  '/receiver/claimed': typeof ReceiverClaimedRoute
  '/donor': typeof DonorIndexRoute
  '/receiver': typeof ReceiverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/donor/create': typeof DonorCreateRoute
  '/receiver/claimed': typeof ReceiverClaimedRoute
  '/donor/': typeof DonorIndexRoute
  '/receiver/': typeof ReceiverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/donor/create'
    | '/receiver/claimed'
    | '/donor/'
    | '/receiver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/donor/create'
    | '/receiver/claimed'
    | '/donor'
    | '/receiver'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/donor/create'
    | '/receiver/claimed'
    | '/donor/'
    | '/receiver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DonorCreateRoute: typeof DonorCreateRoute
  ReceiverClaimedRoute: typeof ReceiverClaimedRoute
  DonorIndexRoute: typeof DonorIndexRoute
  ReceiverIndexRoute: typeof ReceiverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiver/': {
      id: '/receiver/'
      path: '/receiver'
      fullPath: '/receiver/'
      preLoaderRoute: typeof ReceiverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/': {
      id: '/donor/'
      path: '/donor'
      fullPath: '/donor/'
      preLoaderRoute: typeof DonorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiver/claimed': {
      id: '/receiver/claimed'
      path: '/receiver/claimed'
      fullPath: '/receiver/claimed'
      preLoaderRoute: typeof ReceiverClaimedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/create': {
      id: '/donor/create'
      path: '/donor/create'
      fullPath: '/donor/create'
      preLoaderRoute: typeof DonorCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DonorCreateRoute: DonorCreateRoute,
  ReceiverClaimedRoute: ReceiverClaimedRoute,
  DonorIndexRoute: DonorIndexRoute,
  ReceiverIndexRoute: ReceiverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
